[workspace]
members = ["packages/*"]

[workspace.package]
name = "shinigami"
description = "Bitcoin Script Engine"
version = "0.1.0"
cairo-version = "2.8.2"
edition = "2024_07"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/keep-starknet-strange/shinigami.git"

[workspace.dependencies]
ripemd160 = { git = "https://github.com/j1mbo64/ripemd160_cairo.git", rev = "833e07d7d074d4ee51ceb40a5bcb4af2fe6898f3" }
sha1 = { git = "https://github.com/j1mbo64/sha1_cairo.git", rev = "2b65bc00a829bdcc244c140d0f31feda32f8d2c4" }
cairo_test = "2.8.2"
