#!/usr/bin/env python3
"""Generates packages/tests/src/tests/test_core_regressions.cairo.

    gen_regressions.py <cases.jsonl> <out.cairo>

The tests pin the behaviour that Bitcoin Core's vectors showed to be wrong in this engine, so the
fixes stay covered without downloading the vector files:

- selected cases from script_tests.json and script_assets_test.json, by id;
- tapscript spends built here that need no signature, for OP_SUCCESS handling: a single-leaf
  tree under the NUMS internal key, spent through its script path.
"""
import json
import sys

import vectors

# id -> why it is pinned
SELECTED = {
    "script_assets/0/success": "transaction version above 2^31 (random versions in feature_taproot.py)",
    "script_assets/3/success": "OP_CHECKSIGADD in tapscript",
    "script_assets/11/success": "OP_CODESEPARATOR position in the tapscript signature message",
    "script_assets/658/success": "legacy SIGHASH_SINGLE keeps the output at the input's index",
    "script_assets/1003/success": "legacy SIGHASH_SINGLE without a matching output signs 2^248",
    "script_assets/580/success": "an unknown leaf version succeeds without decoding the script",
    "script_tests/1029": "a 33-byte DER integer is a failing signature, not an encoding error",
    "script_tests/1031": "a zero R is a failing signature, not an encoding error",
    "script_tests/1017": "STRICTENC checks the public key even when the signature is empty",
    "script_tests/1312": "CONST_SCRIPTCODE rejects OP_CODESEPARATOR in an unexecuted branch",
}

CONSENSUS = "P2SH,DERSIG,NULLDUMMY,CHECKLOCKTIMEVERIFY,CHECKSEQUENCEVERIFY,WITNESS,TAPROOT"


def tapscript_case(name, script, expect_valid, why):
    """A one-input spend of a single-leaf taproot output through the leaf `script`."""
    output, control_block = vectors.single_leaf_taproot(script)
    amount = 100000
    credit = {
        "version": (1).to_bytes(4, "little"),
        "vin": [{"outpoint": b"\x00" * 32 + b"\xff" * 4, "script_sig": b"\x00\x00",
                 "sequence": b"\xff" * 4, "witness": []}],
        "vout": [{"value": amount.to_bytes(8, "little"), "script_pubkey": output}],
        "locktime": b"\x00" * 4,
    }
    spend = {
        "version": (2).to_bytes(4, "little"),
        "vin": [{"outpoint": vectors.txid(credit) + b"\x00" * 4, "script_sig": b"",
                 "sequence": b"\xff" * 4, "witness": [script, control_block]}],
        "vout": [{"value": amount.to_bytes(8, "little"), "script_pubkey": b"\x51"}],
        "locktime": b"\x00" * 4,
    }
    return {
        "id": name,
        "why": why,
        "expect_valid": expect_valid,
        "tx": vectors.serialize_tx(spend).hex(),
        "prevouts": [(amount, output.hex())],
        "index": 0,
        "flags": vectors.parse_flags(CONSENSUS),
    }


def from_args(case):
    """Recovers transaction, prevouts, index and flags from a case's serialized arguments."""
    felts = [int(x, 16) for x in case["args"]]
    pos = 0

    def take():
        nonlocal pos
        pos += 1
        return felts[pos - 1]

    def take_bytes():
        words = take()
        data = b"".join(take().to_bytes(31, "big") for _ in range(words))
        pending, pending_len = take(), take()
        return data + pending.to_bytes(pending_len, "big")

    tx = take_bytes()
    prevouts = [(take(), take_bytes().hex()) for _ in range(take())]
    return tx.hex(), prevouts, take(), take()


def main():
    cases_path, out_path = sys.argv[1:3]
    by_id = {}
    for line in open(cases_path):
        case = json.loads(line)
        if case["id"] in SELECTED:
            by_id[case["id"]] = case
    missing = set(SELECTED) - set(by_id)
    assert not missing, missing

    tests = []
    for case_id, why in SELECTED.items():
        case = by_id[case_id]
        tx, prevouts, index, flags = from_args(case)
        tests.append({"id": case_id, "why": why, "vector": case["description"],
                      "expect_valid": case["expect_valid"], "tx": tx, "prevouts": prevouts,
                      "index": index, "flags": flags})
    tests += [
        tapscript_case("opsuccess_254", bytes([0xFE]), True, "OP_SUCCESS254 makes the spend valid"),
        tapscript_case("opsuccess_187", bytes([0xBB]), True, "OP_SUCCESS187 makes the spend valid"),
        tapscript_case("opsuccess_80", bytes([0x50]), True, "OP_RESERVED is OP_SUCCESS80 in tapscript"),
        tapscript_case("invalidopcode_255", bytes([0xFF]), False,
                       "0xff is OP_INVALIDOPCODE, not an OP_SUCCESS: the spend is invalid"),
        tapscript_case("invalidopcode_255_after_true", bytes([0x51, 0xFF]), False,
                       "an executed 0xff fails the script even after a true value"),
    ]

    out = []
    w = out.append
    w("// Generated by scripts/core_vectors/gen_regressions.py. Each test pins a behaviour that")
    w("// Bitcoin Core's script test vectors showed to be wrong in this engine.")
    w("")
    w("use shinigami_engine::engine::EngineImpl;")
    w("use shinigami_engine::hash_cache::HashCacheImpl;")
    w("use shinigami_engine::transaction::{EngineInternalTransactionTrait, UTXO};")
    w("use shinigami_utils::bytecode::hex_to_bytecode;")
    w("")
    w("fn verify(")
    w("    tx_hex: ByteArray, prevouts: Array<(i64, ByteArray)>, index: u32, flags: u32,")
    w(") -> Result<(), felt252> {")
    w("    let mut utxos: Array<UTXO> = array![];")
    w("    for prevout in prevouts {")
    w("        let (amount, script_hex) = prevout;")
    w("        utxos")
    w("            .append(")
    w("                UTXO { amount, pubkey_script: hex_to_bytecode(@script_hex), block_height: 0 },")
    w("            );")
    w("    };")
    w("    let transaction = EngineInternalTransactionTrait::deserialize(")
    w("        hex_to_bytecode(@tx_hex), 0, utxos.clone(),")
    w("    );")
    w("    let prevout = utxos.at(index);")
    w("    let hash_cache = HashCacheImpl::new(@transaction);")
    w("    let mut engine = EngineImpl::new(")
    w("        prevout.pubkey_script, @transaction, index, flags, *prevout.amount, @hash_cache,")
    w("    )?;")
    w("    engine.execute()?;")
    w("    Result::Ok(())")
    w("}")
    for t in tests:
        name = t["id"].replace("/", "_")
        w("")
        w(f"// {t['why']}")
        if "vector" in t:
            w(f"// {t['id']}: {t['vector']}"[:100])
        w("#[test]")
        w(f"fn test_{name}() {{")
        w("    let res = verify(")
        w(f'        "0x{t["tx"]}",')
        w("        array![")
        for amount, script in t["prevouts"]:
            w(f'            ({amount}, "0x{script}"),')
        w("        ],")
        w(f"        {t['index']},")
        w(f"        {hex(t['flags'])},")
        w("    );")
        if t["expect_valid"]:
            w("    res.unwrap();")
        else:
            w("    assert!(res.is_err());")
        w("}")
    open(out_path, "w").write("\n".join(out) + "\n")
    print(f"wrote {len(tests)} tests to {out_path}")


if __name__ == "__main__":
    main()
