#!/usr/bin/env python3
"""Turns Bitcoin Core's script test vectors into cases for the `run_case` executable.

    vectors.py <script_tests.json> <script_assets_test.json> <out.jsonl>

Each output line is one verification: the spending transaction, the outputs it spends, the input
to check, the flags, and whether Bitcoin Core expects the input to be valid. `args` is the
`Case` struct of packages/core_vectors serialized as Cairo felts.

- script_tests.json (bitcoin/bitcoin, src/test/data): each test is run the way Bitcoin Core's
  script_tests.cpp runs it, in a one-input transaction spending a crediting transaction.
- script_assets_test.json (bitcoin-core/qa-assets, unit_test_data): the Taproot consensus tests
  generated by feature_taproot.py. Each entry gives a transaction, its prevouts and an input, with
  a valid witness ("success") and usually an invalid one ("failure"). Both are checked under the
  entry's own flags.
"""
import decimal
import hashlib
import json
import sys

# ------------------------------------------------------------------ transactions

def compact_size(n):
    if n < 0xFD:
        return bytes([n])
    if n <= 0xFFFF:
        return b"\xfd" + n.to_bytes(2, "little")
    if n <= 0xFFFFFFFF:
        return b"\xfe" + n.to_bytes(4, "little")
    return b"\xff" + n.to_bytes(8, "little")


def read_compact_size(b, i):
    n = b[i]
    if n < 0xFD:
        return n, i + 1
    size = {0xFD: 2, 0xFE: 4, 0xFF: 8}[n]
    return int.from_bytes(b[i + 1:i + 1 + size], "little"), i + 1 + size


def parse_tx(raw):
    i = 4
    tx = {"version": raw[0:4], "vin": [], "vout": []}
    segwit = raw[4] == 0 and raw[5] != 0
    if segwit:
        i += 2
    n, i = read_compact_size(raw, i)
    for _ in range(n):
        outpoint = raw[i:i + 36]
        i += 36
        ln, i = read_compact_size(raw, i)
        script_sig = raw[i:i + ln]
        i += ln
        sequence = raw[i:i + 4]
        i += 4
        tx["vin"].append({"outpoint": outpoint, "script_sig": script_sig, "sequence": sequence, "witness": []})
    n, i = read_compact_size(raw, i)
    for _ in range(n):
        value = raw[i:i + 8]
        i += 8
        ln, i = read_compact_size(raw, i)
        tx["vout"].append({"value": value, "script_pubkey": raw[i:i + ln]})
        i += ln
    if segwit:
        for vin in tx["vin"]:
            n, i = read_compact_size(raw, i)
            for _ in range(n):
                ln, i = read_compact_size(raw, i)
                vin["witness"].append(raw[i:i + ln])
                i += ln
    tx["locktime"] = raw[i:i + 4]
    assert i + 4 == len(raw), "trailing bytes"
    return tx


def serialize_tx(tx, with_witness=True):
    has_witness = with_witness and any(v["witness"] for v in tx["vin"])
    out = tx["version"]
    if has_witness:
        out += b"\x00\x01"
    out += compact_size(len(tx["vin"]))
    for v in tx["vin"]:
        out += v["outpoint"] + compact_size(len(v["script_sig"])) + v["script_sig"] + v["sequence"]
    out += compact_size(len(tx["vout"]))
    for o in tx["vout"]:
        out += o["value"] + compact_size(len(o["script_pubkey"])) + o["script_pubkey"]
    if has_witness:
        for v in tx["vin"]:
            out += compact_size(len(v["witness"]))
            for w in v["witness"]:
                out += compact_size(len(w)) + w
    return out + tx["locktime"]


def sha256(b):
    return hashlib.sha256(b).digest()


def txid(tx):
    """The txid in internal byte order, as it appears in an outpoint."""
    return sha256(sha256(serialize_tx(tx, with_witness=False)))


def parse_txout(raw):
    amount = int.from_bytes(raw[0:8], "little")
    ln, i = read_compact_size(raw, 8)
    assert i + ln == len(raw)
    return amount, raw[i:i + ln]


# ------------------------------------------------------------------ Bitcoin Core's ParseScript

OPCODE_NAMES = {
    0x50: "OP_RESERVED", 0x61: "OP_NOP", 0x62: "OP_VER", 0x63: "OP_IF", 0x64: "OP_NOTIF",
    0x65: "OP_VERIF", 0x66: "OP_VERNOTIF", 0x67: "OP_ELSE", 0x68: "OP_ENDIF", 0x69: "OP_VERIFY",
    0x6a: "OP_RETURN", 0x6b: "OP_TOALTSTACK", 0x6c: "OP_FROMALTSTACK", 0x6d: "OP_2DROP",
    0x6e: "OP_2DUP", 0x6f: "OP_3DUP", 0x70: "OP_2OVER", 0x71: "OP_2ROT", 0x72: "OP_2SWAP",
    0x73: "OP_IFDUP", 0x74: "OP_DEPTH", 0x75: "OP_DROP", 0x76: "OP_DUP", 0x77: "OP_NIP",
    0x78: "OP_OVER", 0x79: "OP_PICK", 0x7a: "OP_ROLL", 0x7b: "OP_ROT", 0x7c: "OP_SWAP",
    0x7d: "OP_TUCK", 0x7e: "OP_CAT", 0x7f: "OP_SUBSTR", 0x80: "OP_LEFT", 0x81: "OP_RIGHT",
    0x82: "OP_SIZE", 0x83: "OP_INVERT", 0x84: "OP_AND", 0x85: "OP_OR", 0x86: "OP_XOR",
    0x87: "OP_EQUAL", 0x88: "OP_EQUALVERIFY", 0x89: "OP_RESERVED1", 0x8a: "OP_RESERVED2",
    0x8b: "OP_1ADD", 0x8c: "OP_1SUB", 0x8d: "OP_2MUL", 0x8e: "OP_2DIV", 0x8f: "OP_NEGATE",
    0x90: "OP_ABS", 0x91: "OP_NOT", 0x92: "OP_0NOTEQUAL", 0x93: "OP_ADD", 0x94: "OP_SUB",
    0x95: "OP_MUL", 0x96: "OP_DIV", 0x97: "OP_MOD", 0x98: "OP_LSHIFT", 0x99: "OP_RSHIFT",
    0x9a: "OP_BOOLAND", 0x9b: "OP_BOOLOR", 0x9c: "OP_NUMEQUAL", 0x9d: "OP_NUMEQUALVERIFY",
    0x9e: "OP_NUMNOTEQUAL", 0x9f: "OP_LESSTHAN", 0xa0: "OP_GREATERTHAN",
    0xa1: "OP_LESSTHANOREQUAL", 0xa2: "OP_GREATERTHANOREQUAL", 0xa3: "OP_MIN", 0xa4: "OP_MAX",
    0xa5: "OP_WITHIN", 0xa6: "OP_RIPEMD160", 0xa7: "OP_SHA1", 0xa8: "OP_SHA256",
    0xa9: "OP_HASH160", 0xaa: "OP_HASH256", 0xab: "OP_CODESEPARATOR", 0xac: "OP_CHECKSIG",
    0xad: "OP_CHECKSIGVERIFY", 0xae: "OP_CHECKMULTISIG", 0xaf: "OP_CHECKMULTISIGVERIFY",
    0xb0: "OP_NOP1", 0xb1: "OP_CHECKLOCKTIMEVERIFY", 0xb2: "OP_CHECKSEQUENCEVERIFY",
    0xb3: "OP_NOP4", 0xb4: "OP_NOP5", 0xb5: "OP_NOP6", 0xb6: "OP_NOP7", 0xb7: "OP_NOP8",
    0xb8: "OP_NOP9", 0xb9: "OP_NOP10", 0xba: "OP_CHECKSIGADD",
}
# As in core_read.cpp: every name is also accepted without its "OP_" prefix.
OPCODES = {}
for _op, _name in OPCODE_NAMES.items():
    OPCODES[_name] = _op
    OPCODES[_name[3:]] = _op


def push_data(data):
    n = len(data)
    if n < 0x4C:
        return bytes([n]) + data
    if n <= 0xFF:
        return b"\x4c" + bytes([n]) + data
    if n <= 0xFFFF:
        return b"\x4d" + n.to_bytes(2, "little") + data
    return b"\x4e" + n.to_bytes(4, "little") + data


def script_num(n):
    if n == 0:
        return b""
    negative, magnitude = n < 0, abs(n)
    out = bytearray()
    while magnitude:
        out.append(magnitude & 0xFF)
        magnitude >>= 8
    if out[-1] & 0x80:
        out.append(0x80 if negative else 0)
    elif negative:
        out[-1] |= 0x80
    return bytes(out)


def push_int(n):
    if n == 0:
        return b"\x00"
    if n == -1 or 1 <= n <= 16:
        return bytes([0x50 + n])
    return push_data(script_num(n))


def parse_script(text):
    out = b""
    for word in text.split():
        if word.isdigit() or (word.startswith("-") and len(word) > 1 and word[1:].isdigit()):
            n = int(word)
            assert -0xFFFFFFFF <= n <= 0xFFFFFFFF, word
            out += push_int(n)
        elif word.startswith("0x") and len(word) > 2:
            out += bytes.fromhex(word[2:])
        elif len(word) >= 2 and word[0] == "'" and word[-1] == "'":
            out += push_data(word[1:-1].encode())
        else:
            out += bytes([OPCODES[word]])
    return out


# ------------------------------------------------------------------ Taproot, for #TAPROOTOUTPUT#

P = 2**256 - 2**32 - 977
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
G = (0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798,
     0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8)
# XOnlyPubKey::NUMS_H in Bitcoin Core: a key with no known discrete logarithm.
NUMS_H = 0x50929B74C1A04954B78B4B6035E97A5E078A5A0F28EC96D547BFEE9ACE803AC0


def point_add(a, b):
    if a is None:
        return b
    if b is None:
        return a
    if a[0] == b[0] and (a[1] + b[1]) % P == 0:
        return None
    if a == b:
        lam = 3 * a[0] * a[0] * pow(2 * a[1], P - 2, P) % P
    else:
        lam = (b[1] - a[1]) * pow(b[0] - a[0], P - 2, P) % P
    x = (lam * lam - a[0] - b[0]) % P
    return x, (lam * (a[0] - x) - a[1]) % P


def point_mul(k, point):
    result = None
    while k:
        if k & 1:
            result = point_add(result, point)
        point = point_add(point, point)
        k >>= 1
    return result


def lift_x(x):
    y = pow((x * x * x + 7) % P, (P + 1) // 4, P)
    assert y * y % P == (x * x * x + 7) % P
    return x, y if y % 2 == 0 else P - y


def tagged_hash(tag, msg):
    t = sha256(tag.encode())
    return sha256(t + t + msg)


def single_leaf_taproot(script):
    """Output script and control block for a tree with one tapscript leaf, internal key NUMS_H."""
    leaf = tagged_hash("TapLeaf", b"\xc0" + compact_size(len(script)) + script)
    internal = NUMS_H.to_bytes(32, "big")
    tweak = int.from_bytes(tagged_hash("TapTweak", internal + leaf), "big")
    assert tweak < N
    q = point_add(lift_x(NUMS_H), point_mul(tweak, G))
    output = b"\x51\x20" + q[0].to_bytes(32, "big")
    control_block = bytes([0xC0 | (q[1] & 1)]) + internal
    return output, control_block


# ------------------------------------------------------------------ Shinigami flags

FLAGS = {
    "": 0, "NONE": 0, "P2SH": 0x1, "NULLDUMMY": 0x2, "DISCOURAGE_UPGRADABLE_NOPS": 0x4,
    "CHECKLOCKTIMEVERIFY": 0x8, "CHECKSEQUENCEVERIFY": 0x10, "CLEANSTACK": 0x20, "DERSIG": 0x40,
    "LOW_S": 0x80, "MINIMALDATA": 0x100, "NULLFAIL": 0x200, "SIGPUSHONLY": 0x400,
    "STRICTENC": 0x800, "WITNESS": 0x1000, "DISCOURAGE_UPGRADABLE_WITNESS_PROGRAM": 0x2000,
    "MINIMALIF": 0x4000, "WITNESS_PUBKEYTYPE": 0x8000, "TAPROOT": 0x10000,
    "DISCOURAGE_UPGRADABLE_TAPROOT_VERSION": 0x20000, "DISCOURAGE_OP_SUCCESS": 0x40000,
    "DISCOURAGE_UPGRADABLE_PUBKEYTYPE": 0x80000, "CONST_SCRIPTCODE": 0x100000,
}


def parse_flags(text):
    value = 0
    for name in text.split(","):
        value |= FLAGS[name]
    return value


# ------------------------------------------------------------------ Cairo serialization

FIELD_PRIME = 2**251 + 17 * 2**192 + 1


def ser_bytes(b):
    words = [b[i:i + 31] for i in range(0, len(b) - len(b) % 31, 31)]
    pending = b[len(words) * 31:]
    return [len(words)] + [int.from_bytes(w, "big") for w in words] + [int.from_bytes(pending, "big"), len(pending)]


def case_args(transaction, prevouts, index, flags):
    felts = ser_bytes(transaction) + [len(prevouts)]
    for amount, script in prevouts:
        felts += [amount % FIELD_PRIME] + ser_bytes(script)
    return [hex(x) for x in felts + [index, flags]]


# ------------------------------------------------------------------ the two vector files

def script_tests(path):
    for number, test in enumerate(json.load(open(path))):
        if not (isinstance(test, list) and len(test) >= 4):
            continue
        witness, amount, script = [], 0, b""
        pos = 0
        if isinstance(test[0], list):
            for element in test[0][:-1]:
                if element.startswith("#SCRIPT#"):
                    script = parse_script(element[len("#SCRIPT#"):])
                    witness.append(script)
                elif element == "#CONTROLBLOCK#":
                    witness.append(single_leaf_taproot(script)[1])
                else:
                    witness.append(bytes.fromhex(element))
            amount = int(decimal.Decimal(str(test[0][-1])) * 100000000)
            pos = 1
        script_sig_text, script_pubkey_text, flags_text, expected = test[pos:pos + 4]
        comment = test[pos + 4] if len(test) > pos + 4 else ""
        script_sig = parse_script(script_sig_text)
        if script_pubkey_text == "0x51 0x20 #TAPROOTOUTPUT#":
            script_pubkey = single_leaf_taproot(script)[0]
        else:
            script_pubkey = parse_script(script_pubkey_text)

        # BuildCreditingTransaction and BuildSpendingTransaction in Bitcoin Core.
        credit = {
            "version": (1).to_bytes(4, "little"),
            "vin": [{"outpoint": b"\x00" * 32 + b"\xff" * 4, "script_sig": b"\x00\x00",
                     "sequence": b"\xff" * 4, "witness": []}],
            "vout": [{"value": amount.to_bytes(8, "little"), "script_pubkey": script_pubkey}],
            "locktime": b"\x00" * 4,
        }
        spend = {
            "version": (1).to_bytes(4, "little"),
            "vin": [{"outpoint": txid(credit) + b"\x00" * 4, "script_sig": script_sig,
                     "sequence": b"\xff" * 4, "witness": witness}],
            "vout": [{"value": amount.to_bytes(8, "little"), "script_pubkey": b""}],
            "locktime": b"\x00" * 4,
        }
        yield {
            "id": f"script_tests/{number}",
            "source": "script_tests",
            "category": expected,
            "flags": flags_text,
            "expect_valid": expected == "OK",
            "description": f"{script_sig_text} | {script_pubkey_text} | {flags_text} | {expected} | {comment}"[:300],
            "args": case_args(serialize_tx(spend), [(amount, script_pubkey)], 0, parse_flags(flags_text)),
        }


def script_assets(path):
    raw = open(path).read().strip().rstrip(",")
    if not raw.startswith("["):
        raw = "[" + raw + "]"
    for number, test in enumerate(json.loads(raw)):
        tx = parse_tx(bytes.fromhex(test["tx"]))
        prevouts = [parse_txout(bytes.fromhex(p)) for p in test["prevouts"]]
        assert len(prevouts) == len(tx["vin"])
        index, flags = test["index"], parse_flags(test["flags"])
        for part, expect_valid in (("success", True), ("failure", False)):
            if part not in test:
                continue
            tx["vin"][index]["script_sig"] = bytes.fromhex(test[part]["scriptSig"])
            tx["vin"][index]["witness"] = [bytes.fromhex(w) for w in test[part]["witness"]]
            yield {
                "id": f"script_assets/{number}/{part}",
                "source": "script_assets",
                "category": test["comment"].split("/")[0],
                "flags": test["flags"],
                "expect_valid": expect_valid,
                "description": f"{test['comment']} | {test['flags']}" + (" | final" if test.get("final") else ""),
                "args": case_args(serialize_tx(tx), prevouts, index, flags),
            }


def main():
    script_tests_path, assets_path, out_path = sys.argv[1:4]
    count = 0
    with open(out_path, "w") as out:
        for case in list(script_tests(script_tests_path)) + list(script_assets(assets_path)):
            out.write(json.dumps(case) + "\n")
            count += 1
    print(f"wrote {count} cases to {out_path}")


if __name__ == "__main__":
    main()
